CREATE TABLE GL_JE_LINES (
  JE_HEADER_ID            INTEGER,
  JE_LINE_NUM             INTEGER,
  CODE_COMBINATION_ID     INTEGER,
  ENTERED_DR              DECIMAL(18,2)
  ENTERED_CR              DECIMAL(18,2)
  ACCOUNTED_DR            DECIMAL(18,2)
  ACCOUNTED_CR            DECIMAL(18,2)
  CURRENCY_CODE           VARCHAR(10)
  DESCRIPTION             VARCHAR(255)
  PERIOD_NAME             VARCHAR(10),
  EFFECTIVE_DATE          DATE,
  CREATION_DATE           DATE,
  );

CREATE TABLE GL_JE_HEADER (
  JE_HEADER_ID           INTEGER,
  LEDGER_ID              INTEGER,
  JE_SOURCE              VARCHAR(20),
  NAME                   VARCHAR(255),
  CURRENCY_CODE          VARCHAR(20),
  STATUS                 VARCHAR(10),
  ACTUAL_FLAG            VARCHAR(10),
  CREATED_BY             VARCHAR(20),
  JE_BATCH_ID            INTEGER,
  DESCRIPTION            VARCHAR(255),
  REVERSED_JE_HEADER_ID  INTEGER,
  );

CREATE TABLE GL_JE_CODE_COMBINATIONS (
  CODE_COMBINATION_ID    INTEGER,
  ACCOUNT_TYPE           VARCHAR(20),
  SUMMARY_FLAG           VARCHAR(20),
  SEGMENT1               INTEGER,
  SEGMENT2               INTEGER,
  SEGMENT3               INTEGER,
  SEGMENT4               INTEGER,
  );

CREATE TABLE GL_JE_BATCHES (
  JE_BATCH_ID            INTEGER,
  NAME                   VARCHAR(255),
  DESCRIPTION            VARCHAR(255),
  );

CREATE TABLE FND_USER (
  USER_ID                INTEGER,
  USER_NAME              VARCHAR(20),
  USER_DESCRIPTION       VARCHAR(20),
);

CREATE TABLE GL_LEDGERS (
  LEDGER_ID              INTEGER,
  LEDGER_NAME            VARCHAR(20),
  DESCRIPTION            VARCHAR(20),
  LEDGER_CATEGORY_CODE   VARCHAR(20),
);

CREATE TABLE GL_BALANCES (
  LEDGER_ID              INTEGER,
  CODE_COMBINATION_ID    INTEGER,
  CURRENCY_CODE          VARCHAR(20),
  PERIOD_NAME            VARCHAR(20),
  PERIOD_NET_DR          DECIMAL(18,2),
  PERIOD_NET_CR          DECIMAL(18,2),
  BEGIN_BALANCE_DR       DECIMAL(18,2),
  BEGIN_BALANCE_CR       DECIMAL(18,2),
);

CREATE TABLE FX_RATES (
  FROM_CURRENCY          VARCHAR(10),
  TO_CURRENCY            VARCHAR(10),
  PERIOD_NAME            VARCHAR(10),
  RATE_TYPE              VARCHAR(20),
  RATE_DATE              DATE,
  CONVERSION_RATE        DECIMAL(18,6),
);





  









