WITH JOURNAL_BASE AS (
  SELECT
  L.JE_HEADER_ID, 
  L.JE_LINE_NUM,
  L.CODE_COMBINATION_ID,
  L.ENTERED_DR,
  L.ENTERED_CR,
  (L.ENTERED_DR - L.ENTERED_CR) AS ENTERED_NET,
  L.ACCOUNTED_DR,
  L.ACCOUNTED_CR,
  (L.ACCOUNTED_DR - L.ACCOUNTED_CR) AS ACCOUNTED_NET,
  L.CURRENCY_CODE AS LINE_CURRENCY_CODE
  L.DESCRIPTION AS LINE_DESCRIPTION,
  L.PERIOD_NAME,
  L.EFFECTIVE_DATE,
  L.CREATION_DATE,
  H.JE_HEADER_ID,
  H.LEDGER_ID,
  H.JE_SOURCE,
  H.NAME AS HEADER_NAME,
  H.CURRENCY_CODE AS HEADER_CURRENCY_CODE,
  H.STATUS,
  H.ACTUAL_FLAG,
  H.CREATED_BY,
  H.JE_BATCH_ID,
  H.DESCRIPTION AS HEADER_DESCRIPTION,
  H.REVERSED_JE_HEADER_ID,
  CC.CODE_COMBINATION_ID,
  CC.ACCOUNT_TYPE,
  CASE 
  WHEN CC.ACCOUNT_TYPE IN ('A', 'O', 'L') THEN "BS"
  WHEN CC.ACCOUNT_TYPE IN ('E', 'R') THEN "PL"
  ELSE "OTHERS"
  END AS BS_PL_FLAG
  CC.SUMMARY_FLAG,
  CC.SEGMENT1 AS COMPANY_CODE,
  CC.SEGMENT2 AS COST_CENTRE_CODE,
  CC.SEGMENT3 AS ACCOUNT_CODE,
  CC.SEGMENT4 AS INTERCOMPANY_FLAG,
  B.JE_BATCH_ID,
  B.NAME AS BATCH_NAME,
  B.DESCRIPTION AS BATCH_DESCRIPTION,
  U.USER_ID,
  U.USER_NAME,
  U.USER_DESCRIPTION,
  LED.LEDGER_ID,
  LED.LEDGER_NAME,
  LED.DESCRIPTION AS LEDGER_DESCRIPTION,
  LED.LEDGER_CATEGORY_CODE

  FROM GL_JE_LINES L
  LEFT JOIN GL_JE_HEADER H
  ON L.JE_HEADER_ID = H.JE_HEADER_ID
  LEFT JOIN GL_CODE_COMBINATIONS CC
  ON L.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
  LEFT JOIN GL_JE_BATCH B
  ON H.JE_BATCH_ID = B.JE_BATCH_ID
  LEFT JOIN FND_USER U
  ON H.CREATED_BY = U.USER_ID
  LEFT JOIN GL_LEDGERS LED
  ON H.LEDGER_ID = LED.LEDGER_ID
  ),
  
JOURNAL_POPULATION AS (

  SELECT * 
  FROM JOURNAL_BASE
  WHERE H.STATUS = 'P'
  AND H.ACTUAL_FLAG = 'A'
  AND LED.LEDGER_CATEGORY_CODE = 'PRIMARY')

SELECT *
FROM JOURNAL_POPULATION







  
